---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-2560a741
  subnet_id: subnet-5b32ef02
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "ecala_testkitchenS>"
    created-by: "test-kitchen"
    user: Administrator

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-6
    transport:
      username: centos
      ssh_key:  ~\.ssh\id_rsa
    driver_config:
      user_data: ~\user_data

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
